<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RollForward>LatestMajor</RollForward>
        <ImplicitUsings>disable</ImplicitUsings>
        <AssemblyName>luadec</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../src/LuaToolkit.csproj" />
    </ItemGroup>
</Project>